version: 1
disable_existing_loggers: false

formatters:
  console:
    format: "%(asctime)s [%(levelname)-8s] %(filename)s (%(lineno)s): %(message)s"
    datefmt: "%H:%M:%S"

handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: console

loggers:
  root:
    level: INFO
    handlers: [console]
  discord.gateway:
    level: WARNING
    handlers: [console]
